export const provinceDataMap = [
  { province_id: 1, name: 'ACEH', logo: '/images/logo-provinsi/aceh.png' },
  { province_id: 2, name: 'SUMATERA UTARA', logo: '/images/logo-provinsi/sumatera-utara.png' },
  { province_id: 3, name: 'SUMATERA BARAT', logo: '/images/logo-provinsi/sumatera-barat.png' },
  { province_id: 4, name: 'RIAU', logo: '/images/logo-provinsi/riau.png' },
  { province_id: 5, name: 'JAMBI', logo: '/images/logo-provinsi/jambi.png' },
  { province_id: 6, name: 'SUMATERA SELATAN', logo: '/images/logo-provinsi/sumatera-selatan.png' },
  { province_id: 7, name: 'BENGKULU', logo: '/images/logo-provinsi/bengkulu.png' },
  { province_id: 8, name: 'LAMPUNG', logo: '/images/logo-provinsi/lampung.png' },
  { province_id: 9, name: 'KEPULAUAN BANGKA BELITUNG', logo: '/images/logo-provinsi/kepulauan-bangka-belitung.png' },
  { province_id: 10, name: 'KEPULAUAN RIAU', logo: '/images/logo-provinsi/kepulauan-riau.png' },
  { province_id: 11, name: 'DKI JAKARTA', logo: '/images/logo-provinsi/dki-jakarta.png' },
  { province_id: 12, name: 'JAWA BARAT', logo: '/images/logo-provinsi/jawa-barat.png' },
  { province_id: 13, name: 'JAWA TENGAH', logo: '/images/logo-provinsi/jawa-tengah.png' },
  { province_id: 14, name: 'DAERAH ISTIMEWA YOGYAKARTA', logo: '/images/logo-provinsi/daerah-istimewa-yogyakarta.png' },
  { province_id: 15, name: 'JAWA TIMUR', logo: '/images/logo-provinsi/jawa-timur.png' },
  { province_id: 16, name: 'BANTEN', logo: '/images/logo-provinsi/banten.png' },
  { province_id: 17, name: 'BALI', logo: '/images/logo-provinsi/bali.png' },
  { province_id: 18, name: 'NUSA TENGGARA BARAT', logo: '/images/logo-provinsi/nusa-tenggara-barat.png' },
  { province_id: 19, name: 'NUSA TENGGARA TIMUR', logo: '/images/logo-provinsi/nusa-tenggara-timur.png' },
  { province_id: 20, name: 'KALIMANTAN BARAT', logo: '/images/logo-provinsi/kalimantan-barat.png' },
  { province_id: 21, name: 'KALIMANTAN TENGAH', logo: '/images/logo-provinsi/kalimantan-tengah.png' },
  { province_id: 22, name: 'KALIMANTAN SELATAN', logo: '/images/logo-provinsi/kalimantan-selatan.png' },
  { province_id: 23, name: 'KALIMANTAN TIMUR', logo: '/images/logo-provinsi/kalimantan-timur.png' },
  { province_id: 24, name: 'KALIMANTAN UTARA', logo: '/images/logo-provinsi/kalimantan-utara.png' },
  { province_id: 25, name: 'SULAWESI UTARA', logo: '/images/logo-provinsi/sulawesi-utara.png' },
  { province_id: 26, name: 'SULAWESI TENGAH', logo: '/images/logo-provinsi/sulawesi-tengah.png' },
  { province_id: 27, name: 'SULAWESI SELATAN', logo: '/images/logo-provinsi/sulawesi-selatan.png' },
  { province_id: 28, name: 'SULAWESI TENGGARA', logo: '/images/logo-provinsi/sulawesi-tenggara.png' },
  { province_id: 29, name: 'GORONTALO', logo: '/images/logo-provinsi/gorontalo.png' },
  { province_id: 30, name: 'SULAWESI BARAT', logo: '/images/logo-provinsi/sulawesi-barat.png' },
  { province_id: 31, name: 'MALUKU', logo: '/images/logo-provinsi/maluku.png' },
  { province_id: 32, name: 'MALUKU UTARA', logo: '/images/logo-provinsi/maluku-utara.png' },
  { province_id: 33, name: 'PAPUA', logo: '/images/logo-provinsi/papua.png' },
  { province_id: 34, name: 'PAPUA BARAT', logo: '/images/logo-provinsi/papua-barat.png' },
  { province_id: 35, name: 'PAPUA SELATAN', logo: '/images/logo-provinsi/papua-selatan.png' },
  { province_id: 36, name: 'PAPUA TENGAH', logo: '/images/logo-provinsi/papua-tengah.png' },
  { province_id: 37, name: 'PAPUA PEGUNUNGAN', logo: '/images/logo-provinsi/papua-pegunungan.png' },
  { province_id: 38, name: 'PAPUA BARAT DAYA', logo: '/images/logo-provinsi/papua-barat-daya.png' },
];
